[build]
builder = "RAILPACK"

[deploy]
startCommand = "npm start"
numReplicas = 0
sleepApplication = true
restartPolicyType = "NEVER"

[deploy.healthcheck]
path = "/health"
timeout = 10
interval = 30
